import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import cn from "@/utils/cn";
import CartProvider from "@/context/cartContext";
import { Toaster } from "@/components/toaster";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={cn(inter.className, "bg-[#1d2021] px-[40px]")}>
        <NextTopLoader color="#fa421d" showSpinner={false} />
        <CartProvider>
          <div className="flex flex-col">
            <Navbar />
            <div className="py-[130px]">{children}</div>
          </div>
        </CartProvider>
        <Toaster />
      </body>
    </html>
  );
}
